prod: # this needs to match the profile: in your dbt_project.yml file
  target: prod
  outputs:
    prod:
      type: postgres
      user: "{{ env_var('DWH_USERNAME') }}"
      password: "{{ env_var('DWH_PASSWORD') }}"
      host: "{{ env_var('DWH_HOST') }}"
      port: "{{ env_var('DWH_PORT') | int }}"
      database: "{{ env_var('DWH_DB') }}"
      schema: dbt
      threads: 4