{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: {{ .name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .key }}
{{- end }}