apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvPath | quote }}
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token