"""
    RU: Пример создания динамических операций.
    EN: An example of creating dynamic operations.
"""


import dagster as dg




tables_to_load = [
    "aaa",
    "bbb",
    "ccc"
]


@dg.op(
    config_schema={
        "tables_to_load": dg.Field([str], tables_to_load)
    },
    out=dg.DynamicOut())
def generate_dynamic_outputs(context: dg.OpExecutionContext):
    for i in context.op_config["tables_to_load"]:
        yield dg.DynamicOutput(value=i, mapping_key=f"key_{i}")


@dg.op
def process_dynamic_output(context: dg.OpExecutionContext, value: str):
    context.log.info(value)
    return value   


@dg.job(
    description= """
                    RU: Пример создания job из динамических операций.\n
                        Все зависимости операций указываются при создании джоба, по аналогии с джобом из базовых операций.\n
                        Данный джоб создает динамическую операцию для каждого значения, полученного из generate_dynamic_outputs.\n\n
                        \n
                    EN: An example of creating a job from dynamic operations.\n
                        All operation dependencies are specified when creating the job, similar to a job from basic operations.\n
                        This job creates a dynamic operation for each value generated by generate_dynamic_outputs.\n
                """
)
def dynamic_output_op_example_job():
    dynamic_outputs = generate_dynamic_outputs()
    dynamic_outputs.map(process_dynamic_output)