apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-celery-executor
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.dagster.celeryExecutor.replicas }}
  selector:
    matchLabels:
      app: dagster-celery-executor
  template:
    metadata:
      labels:
        app: dagster-celery-executor
    spec:
      terminationGracePeriodSeconds: {{ .Values.dagster.celeryExecutor.terminationGracePeriodSeconds }}
      containers:
        - name: dagster-celery-executor
          image: {{ .Values.dagster.image }}
          imagePullPolicy: IfNotPresent
          command: ["dagster-celery", "worker", "start", "-A", "celery_app.app"]
          env:
            - name: PYTHONPATH
              value: /opt/dagster/app
            - name: DAGSTER_HOME
              value: /opt/dagster/app/dagster_home
            - name: CELERY_WORKER_CONCURRENCY
              value: {{ .Values.dagster.celeryExecutor.concurrency | quote }}
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: celery-credentials
            - secretRef:
                name: dwh-credentials
          volumeMounts:
            {{- if .Values.dagster.hostPath.enabled }}
            - name: app-code
              mountPath: /opt/dagster/app
            {{- end }}
            - name: dagster-config
              mountPath: /opt/dagster/app/dagster_home/dagster.yaml
              subPath: dagster.yaml
          resources:
            {{- toYaml .Values.dagster.celeryExecutor.resources | nindent 12 }}
      volumes:
        {{- if .Values.dagster.hostPath.enabled }}
        - name: app-code
          hostPath:
            path: {{ .Values.dagster.hostPath.appPath }}
            type: Directory
        {{- end }}
        - name: dagster-config
          configMap:
            name: dagster-config