apiVersion: v1
kind: Service
metadata:
  name: dagster-user-code
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dagster-user-code
  ports:
    - name: grpc
      port: 4000
      targetPort: grpc