name: dagster-dbt

services:

  # This service runs the postgres database used by dagster to store launches, schedules, and event logs.
  dagster-postgresql:
    container_name: dagster-postgresql
    image: postgres:17
    ports: 
      - ${PG_PORT}:${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 3
    depends_on:
      dbt-docs-and-prepare-project:
        condition: service_started
  
  dagster-rabbitmq:
    container_name: dagster-rabbitmq
    image: rabbitmq:4.1.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: ${DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  dagster-redis:
    container_name: dagster-redis
    image: redis:8.0.6-alpine
    ports: 
        - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  dagster-flower:
    container_name: dagster-flower
    image: mher/flower:2.0.1
    environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - FLOWER_PORT=5555      
    ports:
        - 5555:5555
    depends_on:
      dagster-rabbitmq:
        condition: service_healthy

  # This service creates the necessary files for dbt (manifest.json, etc.), as well as runs the dbt documentation server.
  dbt-docs-and-prepare-project:
    container_name: dbt-docs-and-prepare-project
    build:
        context: .
        dockerfile: Dockerfile_dbt_docs
    image: dbt-docs-image
    ports:
        - 8001:8001
    environment:
      DWH_USER: ${DWH_USER}
      DWH_PASSWORD: ${DWH_PASSWORD}
      DWH_HOST: ${DWH_HOST}
      DWH_PORT: ${DWH_PORT}
      DWH_DB: ${DWH_DB}
    working_dir: /opt/dagster/app/dbt/projects
    entrypoint: bash -c "dbt parse && dbt docs generate && dbt docs serve --host 0.0.0.0 --port 8001"
    volumes:
      - ./app/dbt/:/opt/dagster/app/dbt/

  # This service runs a code server that downloads custom code.
  dagster-user-code:
    container_name: dagster-user-code
    build:
      context: .
      dockerfile: Dockerfile
    image: dagster-image
    entrypoint: dagster api grpc -h 0.0.0.0 -p 4000 -f dagster_easy/definitions.py
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      dbt-docs-and-prepare-project:
        condition: service_started
    volumes:
      - ./app/:/opt/dagster/app/

  # This service is running under a dagster web server.
  dagster-webserver:
    container_name: dagster-webserver
    build:
      context: .
      dockerfile: Dockerfile
    image: dagster-image
    working_dir: /opt/dagster/app/dagster_home
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
    volumes:
      - ./app/dagster_home/storage/:/opt/dagster/app/dagster_home/storage
      - ./app/dagster_home/dagster.yaml:/opt/dagster/app/dagster_home/dagster.yaml
      - ./app/dagster_home/workspace.yaml:/opt/dagster/app/dagster_home/workspace.yaml
    depends_on:
      dagster-postgresql:
        condition: service_healthy
      dagster-user-code:
        condition: service_started

  # This service starts the dagster-daemon process.
  dagster-daemon:
    container_name: dagster-daemon
    build:
      context: .
      dockerfile: Dockerfile
    image: dagster-image
    working_dir: /opt/dagster/app/dagster_home
    entrypoint:
      - dagster-daemon
      - run
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app/dagster_home/dagster.yaml:/opt/dagster/app/dagster_home/dagster.yaml
      - ./app/dagster_home/workspace.yaml:/opt/dagster/app/dagster_home/workspace.yaml
    depends_on:
      dagster-postgresql:
        condition: service_healthy
      dagster-user-code:
        condition: service_started

  dagster-celery-executor:
    container_name: dagster-celery-executor
    build:
      context: .
      dockerfile: Dockerfile
    image: dagster-image
    environment:
      PYTHONPATH: /opt/dagster/app
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}     
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}       
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      CELERY_WORKER_CONCURRENCY: 10
      DWH_USER: ${DWH_USER}
      DWH_PASSWORD: ${DWH_PASSWORD}
      DWH_HOST: ${DWH_HOST}
      DWH_PORT: ${DWH_PORT}
      DWH_DB: ${DWH_DB}
    entrypoint: dagster-celery worker start -A celery_app.app
    depends_on:
      dagster-postgresql:
        condition: service_healthy
      dagster-rabbitmq:
        condition: service_healthy
      dagster-redis:
        condition: service_healthy
    volumes:
      - ./app/:/opt/dagster/app/


networks:
  default:
    name: data-platform-net
    external: true