apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbt-target
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.dbt.targetStorage }}