apiVersion: v1
kind: Service
metadata:
  name: dagster-webserver
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dagster-webserver
  ports:
    - name: http
      port: 3000
      targetPort: http