externalSecrets:
  refreshInterval: 1m

dagster:
  image: dagster-user-code:latest
  hostPath:
    enabled: true
    appPath: /mnt/projects/dagster-dbt-docker/app
  runLauncher:
    resources:
      requests: {cpu: 200m, memory: 512Mi}
      limits: {cpu: "1", memory: 1Gi}

dbt:
  image: dbt-docs-image:latest